# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
