# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170921_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.Hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='general_practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.Doctor'),
        ),
    ]
